[package]
name = "tls-api-rustls"
version = "0.1.19"
authors = ["Stepan Koltsov <stepan.koltsov@gmail.com>"]
description = "TLS API implementation over rustls crate"
license = "MIT/Apache-2.0"
repository = "https://github.com/stepancheg/rust-tls-api/"
keywords = ["tls"]

[badges]
travis-ci = { repository = "https://github.com/stepancheg/rust-tls-api/", branch = "master" }

[dependencies]
rustls = { version = "0.14", features = ["dangerous_configuration"] }
tls-api = { version = "0.1.19", path = "../api" }
webpki       = "0.18"
webpki-roots = "0.15"

[dev-dependencies]
tls-api-test = { version = "0.1.19", path = "../api-test" }
